name: call test
on:
  workflow_call:
    inputs:
      username:
        description: 'A username passed from the caller workflow'
        default: 'john-doe'
        required: false
        type: string

jobs:
  print-username:
    runs-on: ubuntu-latest

    steps:
      - name: Print the input name to STDOUT
        run: echo ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
      - run: echo ${{ github.run_number }}
      - run: echo $something
      - name: Get Current Time
        uses: josStorer/get-current-time@v2.0.0
        id: current-time
        with:
          format: YYMMDD_HHmmss
          utcOffset: "+09:00"