name: dispatch test
on:
  workflow_dispatch:
    inputs:
      username:
        description: username
        type: string
        default: no name??
        required: true
jobs:
  call:
    name: call name
    uses: ./.github/workflows/action.yml