name: dispatch test
on:
  workflow_dispatch:
    inputs:
      username:
        description: username
        default: no name??
        type: choice
        options:
          - just only one
        required: true
jobs:
  call:
    runs-on: ubuntu-latest
    steps:
      - name: print github
        env:
          GIBHUT_CONTEXT: ${{ toJSON(github) }}
        run: echo $GIBHUT_CONTEXT