name: dispatch test
on:
  workflow_dispatch:
    inputs:
      username:
        description: username
        type: string
        default: no name??
        required: true
jobs:
  call:
    runs-on: ubuntu-latest
    steps:
      - name: call name
        uses: ./.github/workflows/action.yml
        with:
          username: ${{ inputs.username }}